name: Change PR base to dev if main

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  change-base:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.base.ref == 'main' &&
      !contains(github.event.pull_request.title, '[MAIN]')

    steps:
      - name: Change base to dev
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const currentBase = context.payload.pull_request.base.ref;

            if (currentBase === 'main') {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                base: 'dev'
              });
              console.log(`PR #${prNumber} base changed to dev`);
            } else {
              console.log(`PR #${prNumber} already targeting ${currentBase}`);
            }